config/routes.rb
InstructionGuide::Application.routes.draw do
  root :to => "instructionguides#index"
  resources :instructionguides do
    resources :steps
  end

end

app/models/instructionguide.rb
class Instructionguide < ActiveRecord::Base
  attr_accessible :description, :name, :owner
  has_many :steps, dependent: :delete_all
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :instructionguide
  attr_accessible :order, :title
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :instructionguide
  attr_accessible :description, :generate, :model, :order, :rails, :step, :title, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instructionguides_controller.rb
class InstructionguidesController < ApplicationController
before_filter :find_instructionguide, :only => [:show, :edit, :update, :destroy]
	def index
		@instructionguides = Instructionguide.all
	end

	def new
		@instructionguide = Instructionguide.new
	end

	def create
		@instructionguide = Instructionguide.new(params[ :instructionguide])
		if @instructionguide.save
			flash[ :notice] = "Instruction Guide has been created."
			redirect_to @instructionguide
		else
			flash[ :alert] = "Instruction Guide has not been created."
			render :action => "new"	
		end
	end

	def show

	end

	def destroy
		@instructionguide.destroy
		flash[:notice] = "Guide has been deleted."
		redirect_to root_path
	end

	private
	  def find_instructionguide
	  	@instructionguide = Instructionguide.find(params[:id])
	    rescue ActiveRecord::RecordNotFound
	    flash[:alert] = "The instruction guide you were looking" + 
	  				" for could not be found."
	    redirect_to instructionguides_path
	  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
	before_filter :find_instructionguide
	before_filter :find_step, :only => [:show, :edit, :update, :destroy]
	def new
		@step = @instructionguide.steps.build
	end

	def index
		@steps = @instructionguide.steps.order("order asc")
	end

	def show

	end

	def create
		@step = @instructionguide.steps.build(params[:step])
		if @step.save
			flash[:notice] = "Step has been created."
			redirect_to [@instructionguide, @step]
		else
			flash[:alert] = "Step has not been created."
			render :action => "new"
		end
	end

	def edit

	end

	def update
		if @step.update_attributes(params[:step])
			flash[:notice] = "Step has been updated."
			redirect_to [@instructionguide, @step]
		else
			flash[:alert] = "Step has not been updated."
			render :action => "edit"
		end
	end
	def destroy
		@step.destroy
		flash[:notice] = "Step has been deleted."
		redirect_to @instructionguide
	end

	private
	def find_instructionguide
		@instructionguide = Instructionguide.find(params[:instructionguide_id])
	end
	def find_step
	  	@step = @instructionguide.steps.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructionguides_helper.rb
module InstructionguidesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/instructionguides/new.html.erb
<h2>New Instruction Guide</h2>

<%= form_for(@instructionguide) do |f| %>
	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</p>

	<p>
		<%= f.label :owner %><br />
		<%= f.text_field :owner %>
	</p>

	<%= f.submit %>
<% end %>

app/views/instructionguides/show.html.erb
<h2><%= @instructionguide.name %></h2>

<%= link_to "New Step", new_instructionguide_step_path(@instructionguide) %> <br>
<h2>Steps</h2>

<ul id='steps'>
  <% @instructionguide.steps.each do |step| %>
    <li>
      #<%= step.order %> -
      <%= link_to step.title, [@instructionguide, step] %>
    </li>
   <% end %>
</ul>

<%= link_to "All Guides", root_path %>  |
<%= link_to "Delete Guide", instructionguide_path, method: :delete, confirm: "Are you sure you want to delete this guide?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstructionGuide</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
  	 <%= value %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@instructionguide, @step] do |f| %>

  <p>
    <%= f.label :title %><br>
      
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </p>
  <%= f.submit %>
<% end %>

app/views/steps/edit.html.erb
<h2>Editing a step in <%= @instructionguide.name %></h2>
<%= form_for [@instructionguide, @step] do |f| %>

  <p>
    <%= f.label :title %><br>
      
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </p>
  <%= f.submit %>
<% end %>

app/views/steps/index.html.erb
<h2>Instruction Guides</h2>
<ul>
	<% @instructionguides.each do |instructionguide| %>
	  <li><%= link_to instructionguide.name, instructionguide %> </li>
	<% end %>
</ul>

<%= link_to "New Instruction Guide", new_instructionguide_path %>

app/views/steps/new.html.erb
<h2>New Instruction Guide Step</h2>

<%= render "form" %>

app/views/steps/show.html.erb
<h2><%= @step.title %></h2>
<br>
<p>step # <%= @step.order %></p>
<%= link_to "Edit Step", [:edit, @instructionguide, @step] %>
<%= link_to "Delete Step", [@instructionguide, @step], :method => :delete, :confirm => "Are you sure you want to delete this step?" %>
<%= link_to "View Guide", @instructionguide %>